---
abstract: 'Rule based validator on type constraint system'
author:
  - 'Fuji, Goro (gfx) <gfuji@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Validator
name: Data-Validator
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Mouse: 0.93
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Data-Validator.git
version: 0.07
